### PR TITLE
improve qt5 compatibility

### PR DESCRIPTION
**Pull request by fredboudon**
Introduce QtPrintSupport. Add uic for Qt5

### CODE REVIEW

**Comment by pradal** [comment]
We plan (with @openalea/amdt team) to use [qtpy](https://github.com/spyder-ide/qtpy).

**Comment by jwintz** [comment]
> On 8 Dec 2016, at 14:01, Christophe Pradal <notifications@github.com> wrote:
> 
> We plan (with @openalea/amdt <https://github.com/orgs/openalea/teams/amdt> team) to use qtpy <https://github.com/spyder-ide/qtpy>.
> 


Nice to hear about it, we are currently investigating as well. However, we found that Qt.py may be a good solution as well.

Any hints on why qtpy would be better than qt.py ?

**Comment by tkloczko** [comment]
Here a comparison matrix provided by Qt.py 

https://github.com/mottosso/Qt.py#projects-similar-to-qtpy 

For us it is hard to interpret it. 

Regards, 

Thibaud. 

------------------------------------------------- 
Ingénieur d'Expérimentation et de Développement 
Inria CRISAM 
2004, route des lucioles 
06902 Sophia Antipolis 
+33 4 92 38 50 03 

----- Original Message -----

| From: "Julien Wintz" <notifications@github.com>
| To: "openalea/openalea" <openalea@noreply.github.com>
| Cc: "Thibaud Kloczko" <thibaud.kloczko@inria.fr>, "Team mention"
| <team_mention@noreply.github.com>
| Sent: Thursday, 8 December, 2016 3:47:58 PM
| Subject: Re: [openalea/openalea] improve qt5 compatibility (#233)

| > On 8 Dec 2016, at 14:01, Christophe Pradal <notifications@github.com>
| > wrote:
| >
| > We plan (with @openalea/amdt <https://github.com/orgs/openalea/teams/amdt>
| > team) to use qtpy <https://github.com/spyder-ide/qtpy>.
| >

| Nice to hear about it, we are currently investigating as well. However, we
| found that Qt.py may be a good solution as well.

| Any hints on why qtpy would be better than qt.py ?

| —
| You are receiving this because you are on a team that was mentioned.
| Reply to this email directly, view it on GitHub , or mute the thread .

**Comment by pradal** [comment]
What I know is that Spyder and qcode projects are using this binding which is also compatible with Jupyter (and available in conda).
However, I didn't know the Qt.py binding.

**Comment by jwintz** [comment]
That's what appears exactly in the comparaison chart, but it seems that Qt.py is more proefficient, as is able to handle e.g. both python 2.7 and python 3 (which is good for a slow transition), and also the chart points out specific criterion such as PEP8, Standalone, PyPI and Co-existence (even though we I have a idea for this one), that we are currently now not in position to really understand, we need your lights.

Also it seems to be more active, well documented and well maintained.

Could you give us some hint about these criteria ?

PS: Our first tests, outside of oalab because of evident conflict with vpltk, are quite amazing.

  - ju

**Comment by pradal** [comment]
I think that both are available for Python 2.7 and 3 (because Spyder works for both Python version)
Both lib is PEP8 and PyPi (https://pypi.python.org/pypi/QtPy).

The main difference is Qt.py is developed by PySide2 developers and support it while qtpy only supports PySide.

The drawback of Qt.py is that it does not use the same API for choosing either PyQt4 or PyQt5.
qtpy use QT_API (like vtk/mayavi, matplotlib and ipython) while qt.py use QT_PREFERED_API.

But both seems quite simple.

**Pull request merged**
